# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"

  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "SecurityDLL/" # Location of package manifests
    schedule:
      interval: "daily"
    
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "SecurityManager/" # Location of package manifests
    schedule:
      interval: "daily"
      
