name: Live Test
on:
  workflow_dispatch:
  pull_request:
   types: [opened, reopened]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Pre-run Tasks
        run: |
          sudo apt install libsqlite3-dev
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install dependencies
        run: |
          cd ${{ github.workspace }}
          cd ..
          python -m venv pysecenv
          source pysecenv/bin/activate
          sudo chmod -R a+rwx ${{ github.workspace }}
          cd ${{ github.workspace }}
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt
          mkdir openssl-config
          mkdir openssl-install
      - name: Build
        run: |
          cd openssl
          perl Configure --prefix=${{ github.workspace }}/openssl-install --openssldir=${{ github.workspace }}/openssl-config enable-fips
          make -j3 
          sudo make -j3 install
          cd ..
          source ../pysecenv/bin/activate
          pip install -e .
      - name: Run Test
        run: |
          cd ..
          source pysecenv/bin/activate
          sudo chmod -R a+rwx ${{ github.workspace }}
          cd ${{ github.workspace }}
          python -m unittest tests/test_BaseAPIs.py
  