name: Live Test
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          cd ${{ github.workspace }}
          mkdir openssl-config
          mkdir openssl-install
      - name: Build
        run: |
          cd openssl
          perl Configure --prefix=${{ github.workspace }}/openssl/openssl-install --openssldir=${{ github.workspace }}/openssl/openssl-config enable-fips
          make -j3 
          sudo make -j3 install
          cd ..
      - name: Run Test
        run: |
          pip install .
          python -m unittest tests/test_BaseAPIs.py
  
  buildWin:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install VS Tools
        uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: 16.XX
      - name: NASM and Perl
        run: |
            choco install nasm
            echo "C:\Program Files\NASM" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
            choco install strawberryperl
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          cd ${{ github.workspace }}
          mkdir openssl-config
          mkdir openssl-install
      - name: Build
        run: |
          cd openssl
          perl Configure --prefix=${{ github.workspace }}/openssl/openssl-install --openssldir=${{ github.workspace }}/openssl/openssl-config enable-fips
          nmake -j3 
          nmake -j3 install
          cd ..
      - name: Run Test
        run: |
          pip install .
          python -m unittest tests/test_BaseAPIs.py
