name: Live Test
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          cd ${{ github.workspace }}
          mkdir openssl-config
          mkdir openssl-install
      - name: Build
        run: |
          ls
          cd openssl
          ls
          sudo apt install perl
          perl Configure --prefix=${{ github.workspace }}/openssl/openssl-install --openssldir=${{ github.workspace }}/openssl/openssl-config enable-fips
          make
          make install
          cd ..
      - name: Run Test
        run: |
          python -m unittest tests/test_BaseAPIs.py
