name: Code Quality chk
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  workflow_dispatch:
  pull_request:
   types: [opened, reopened]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Review:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: microsoft/DevSkim-Action@v1
        with:
          output-filename: devskim-results.sarif
          output-directory: security
