name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "**Note: this is an automated message send to every issue. It is not meant personally to you. ** Welcome! We hope you like our project! We value your precious feedback, and we always want to improve. However, we would like to request the following: until a human looks at your issue, could you please verify that you have not included copyrighted material that is not owned by either you or by us? If you have, could you please verify that you have a license for the content in question?  Thank you very much in advance!"
        pr-message: "**Note: this is an automated message send to every issue. It is not meant personally to you. ** Welcome! We hope you like our project! We value your precious feedback, and we always want to improve. However, we would like to request the following: until a human looks at your issue, could you please verify that you have not included copyrighted material that is not owned by either you or by us? If you have, could you please verify that you have a license for the content in question?  Thank you very much in advance!"
