name: Live Test
on:
  workflow_dispatch:
  pull_request:
   types: [opened, reopened]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Pre-run Tasks
        run: |
          sudo apt install libsqlite3-dev
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: 'x64'
          cache: 'pip'
      - name: Install dependencies
        run: |
          cd ${{ github.workspace }}
          cd ..
          python -m venv krenv
          source krenv/bin/activate
          sudo chmod -R a+rwx ${{ github.workspace }}
          cd ${{ github.workspace }}
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt
          mkdir kr-openssl-config
          mkdir kr-openssl-install
      - name: Build OSSL
        run: |
          cd openssl
          perl Configure --prefix=${{ github.workspace }}/kr-openssl-install --openssldir=${{ github.workspace }}/kr-openssl-config enable-fips
          make -j3 
          make -j3 install
          cd ..
      - name: Install extension
        run: |
          source ../krenv/bin/activate
          pip install .
      - name: Run Test
        run: |
          cd ..
          source krenv/bin/activate
          sudo chmod -R a+rwx ${{ github.workspace }}
          cd ${{ github.workspace }}
          python -m unittest tests/api.py --verbose
  