name: Live Test and CodeQL CPP
on:
  workflow_dispatch:
  pull_request:
   types: [opened, reopened]
  schedule:
    - cron: '29 4 * * 5'
jobs:
  TestAnalisys:
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: 'cpp'
          config-file: ./.github/code-ql/codeql-config.yml
      - name: Pre-run Tasks
        run: |
          sudo apt install libsqlite3-dev
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: 'x64'
          cache: 'pip'
      - name: Install dependencies
        run: |
          cd ${{ github.workspace }}
          python -m venv krenv
          mkdir ${{ github.workspace }}/krenv/Lib
          mkdir ${{ github.workspace }}/krenv/Lib/site-packages/
          source krenv/bin/activate
          sudo chmod -R a+rwx ${{ github.workspace }}
          cd ${{ github.workspace }}
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt
          mkdir kr-openssl-config
          mkdir kr-openssl-install
      - name: Cache OSSL Build
        id: cache-ossl
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/kr-openssl-*
          key: ubunut-ossl
      - name: Build OSSL
        if: steps.cache-ossl.outputs.cache-hit != 'true'
        run: |
          cd openssl
          perl Configure --prefix=${{ github.workspace }}/kr-openssl-install --openssldir=${{ github.workspace }}/kr-openssl-config enable-fips
          make -j3 
          make -j3 install
          cd ..
      - name: Install extension
        run: |
          cd ${{ github.workspace }}
          source krenv/bin/activate
          pip install .
      - name: Run Test
        run: |
          cd ${{ github.workspace }}
          source krenv/bin/activate
          sudo chmod -R a+rwx ${{ github.workspace }}
          python -m unittest discover -s tests -p "*test*.py" --verbose
      - name: Install AutoBuild depends
        run: python -m pip install pybind11
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
