# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Run a multi-line script
        uses: actions/checkout@v2
        with: 
          script: |
            await octokit.request('PUT /repos/{owner}/{repo}/pulls/{pull_number}/merge', {
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              commit_title: 'Automerge Dependencies'
            })

