name: Release Binaries
on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  buildLinux:
    env:
      CIBW_ARCHS: auto
      CIBW_ENVIRONMENT: LD_LIBRARY_PATH=/project/kr-openssl-install/lib64
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
      - name: Build Extension
        run: |
          python3 -m pip install cibuildwheel
          python3 -m cibuildwheel --output-dir dist
        env:
          CIBW_BEFORE_ALL: |
            cd /project
            yum install -y perl-IPC-Cmd
            yum install -y make
            mkdir kr-openssl-config
            mkdir kr-openssl-install
            cd openssl
            perl Configure --prefix=/project/kr-openssl-install --openssldir=/project/kr-openssl-config enable-fips
            make -j3
            make -j3 install
            cd ..
      - name: Upload Build Result
        uses: actions/upload-artifact@v3
        with:
          name: AutoBuild-Linux-${{ github.event.release.tag_name }}
          path: ${{ github.workspace }}/dist/*.*

  buildWin:
    env:
      CIBW_ARCHS: native
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install VS Tools
        uses: ilammy/msvc-dev-cmd@v1
      - name: NASM and Perl
        run: |
          choco install nasm
          echo "C:\Program Files\NASM" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          choco install strawberryperl
      - name: Install dependencies
        run: |
          cd ${{ github.workspace }}
          py -m pip install --upgrade pip setuptools wheel
      - name: Build OSSL
        run: |
          mkdir kr-openssl-config
          mkdir kr-openssl-install
          cd openssl
          perl Configure --prefix=${{ github.workspace }}/kr-openssl-install --openssldir=${{ github.workspace }}/kr-openssl-config enable-fips
          set CL=/MP
          nmake
          nmake install
      - name: Build Extension
        run: |
          cd ${{ github.workspace }}
          python -m pip install cibuildwheel
          python -m cibuildwheel --output-dir dist
      - name: Upload Build Result
        uses: actions/upload-artifact@v3
        with:
          name: AutoBuild-Windows-${{ github.event.release.tag_name }}
          path: ${{ github.workspace }}/dist/*.*

  buildMac:
    env:
      CIBW_ARCHS: auto64
      CIBW_ENVIRONMENT: LD_LIBRARY_PATH=${{ github.workspace }}/kr-openssl-install/lib64
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
      - name: Build Extension
        run: |
          python3 -m pip install cibuildwheel
          python3 -m cibuildwheel --output-dir dist
        env:
          CIBW_BEFORE_ALL: |
            mkdir kr-openssl-config
            mkdir kr-openssl-install
            cd openssl
            perl Configure --prefix=${{ github.workspace }}/kr-openssl-install --openssldir=${{ github.workspace }}/kr-openssl-config enable-fips
            make -j4
            make -j4 install
            cd ..
      - name: Upload Build Result
        uses: actions/upload-artifact@v3
        with:
          name: AutoBuild-MacOS-${{ github.event.release.tag_name }}
          path: ${{ github.workspace }}/dist/*.*

  releaseBins:
    env:
      GH_TOKEN: ${{ secrets.App }}
    runs-on: ubuntu-latest
    needs: [buildLinux, buildWin]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Create Dir for Build
        run: |
          cd ${{ github.workspace }}
          mkdir dist
      - name: Download Built Windows Extensions
        uses: actions/download-artifact@v3
        with:
          name: AutoBuild-Windows-${{ github.event.release.tag_name }}
          path: ${{ github.workspace }}/dist
      - name: Download Built Linux Extension
        uses: actions/download-artifact@v3
        with:
          name: AutoBuild-Linux-${{ github.event.release.tag_name }}
          path: ${{ github.workspace }}/dist
#      - name: Download Built MacOS Extension
#        uses: actions/download-artifact@v3
#        with:
#          name: AutoBuild-Mac-${{ github.event.release.tag_name }}
#          path: ${{ github.workspace }}/dist
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
#          repository_url: https://test.pypi.org/legacy/
      - name: Upload Build Results to GH Release
        run: |
          gh release upload ${{ github.event.release.tag_name }} dist/*.whl
