name: Release Binaries
on:
  release:
    types: [created]
  
env:
  GH_TOKEN: ${{ secrets.App }}

jobs:
  buildLinux:
    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.9', '3.10']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      - name: Install dependencies
        run: |
          cd ${{ github.workspace }}
          python -m venv krenv
          mkdir ${{ github.workspace }}/krenv/Lib
          mkdir ${{ github.workspace }}/krenv/Lib/site-packages/
          source krenv/bin/activate
          sudo chmod -R a+rwx ${{ github.workspace }}
          cd ${{ github.workspace }}
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt
          mkdir kr-openssl-config
          mkdir kr-openssl-install
      - name: Build OSSL
        run: |
          cd openssl
          perl Configure --prefix=${{ github.workspace }}/kr-openssl-install --openssldir=${{ github.workspace }}/kr-openssl-config enable-fips
          make -j3 
          make -j3 install
          cd ..
      - name: Build Extension
        run: |
          cd ${{ github.workspace }}
          sudo chmod -R a+rwx ${{ github.workspace }}
          source krenv/bin/activate
          python -m pip install --upgrade build
          python -m build --no-isolation 
      - name: Upload Build Result
        uses: actions/upload-artifact@v3
        with:
          name: AutoBuild-Linux-${{ github.event.release.tag_name }}
          path: ${{ github.workspace }}/dist/*.*
  
  buildWin:
    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.9', '3.10']
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      - name: Install VS Tools
        uses: ilammy/msvc-dev-cmd@v1
      - name: NASM and Perl
        run: |
            choco install nasm
            echo "C:\Program Files\NASM" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
            choco install strawberryperl
      - name: Install dependencies
        run: |
          cd ${{ github.workspace }}
          py -m pip install --upgrade pip setuptools wheel
          py -m pip install -r requirements.txt
          mkdir kr-openssl-config
          mkdir kr-openssl-install
      - name: Build OSSL
        run: |
          cd openssl
          perl Configure --prefix=${{ github.workspace }}/kr-openssl-install --openssldir=${{ github.workspace }}/kr-openssl-config enable-fips
          set CL=/MP
          nmake
          nmake install
      - name: Build Extension
        run: |
          cd ${{ github.workspace }}
          py -${{ matrix.python-version }} -m pip install --upgrade build
          py -${{ matrix.python-version }} -m build
      - name: Upload Build Result
        uses: actions/upload-artifact@v3
        with:
          name: AutoBuild-Windows-${{ github.event.release.tag_name }}
          path: ${{ github.workspace }}/dist/*.*

  releaseBins:
    runs-on: ubuntu-latest
    needs: [buildLinux, buildWin]
    steps: 
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Create Dir for Build
        run: |
          cd ${{ github.workspace }}
          mkdir dist
      - name: Download Built Extensions
        uses: actions/download-artifact@v3
        with:
          name: AutoBuild-Windows-${{ github.event.release.tag_name }}
          path: ${{ github.workspace }}/dist
      - name: Download Linux Built Extension
        uses: actions/download-artifact@v3
        with:
          name: AutoBuild-Linux-${{ github.event.release.tag_name }}
          path: ${{ github.workspace }}/dist
      - name: Upload Build Results to Release
        run: |
          gh release upload ${{ github.event.release.tag_name }} dist/*.whl
