name: Test tests
on:
  workflow_dispatch:

jobs:
  buildLinux:
    env:
      CIBW_ARCHS: native
      CIBW_ENVIRONMENT: LD_LIBRARY_PATH=/project/kr-openssl-install/lib64
      CIBW_TEST_COMMAND: |
        python -m krypton --clean
        python -m unittest discover -s {project}/tests -p "*test*.py" --verbose
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
      - name: Build Extension
        run: |
          python3 -m pip install cibuildwheel
          python3 -m cibuildwheel --output-dir dist
        env:
          CIBW_BEFORE_ALL: |
            cd /project
            yum install -y perl-IPC-Cmd
            yum install -y make
            mkdir kr-openssl-config
            mkdir kr-openssl-install
            cd openssl
            perl Configure --prefix=/project/kr-openssl-install --openssldir=/project/kr-openssl-config enable-fips
            make -j3
            make -j3 install
            cd ..
      - name: Upload Build Result
        uses: actions/upload-artifact@v3
        with:
          name: AutoBuild-Linux-${{ github.event.release.tag_name }}
          path: ${{ github.workspace }}/dist/*.*
