name: Greet User!

# Controls when the action will run. 
on:
  pull_request:
    types:
      - opened
  issues:
    types:
      - opened
jobs:
  # This workflow contains a single job called "build"
  run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          curl \
            -X POST \
            -u MBS9Admin:${{ secrets.App }} \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
            -d '{"body":"Welcome to Krypton! Your issue/pull request is recieved and will be picked up by one of our maintainers. Thank you for your patience!"}'
