name: Build Win32 bins
on:
  workflow_dispatch:

jobs:
  buildWin:
    env:
      CIBW_ARCHS: x86
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install VS Tools
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86
      - name: NASM and Perl
        run: |
          choco install nasm
          echo "C:\Program Files\NASM" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          choco install strawberryperl
      - name: Install dependencies
        run: |
          cd ${{ github.workspace }}
          py -m pip install --upgrade pip setuptools wheel
      - name: Build OSSL
        run: |
          cd openssl
          perl Configure VC-WIN32 --prefix=${{ github.workspace }}/kr-openssl-install --openssldir=${{ github.workspace }}/kr-openssl-config enable-fips
          set CL=/MP
          nmake
          nmake install
      - name: Build Extension
        run: |
          cd ${{ github.workspace }}
          python -m pip install cibuildwheel
          python -m cibuildwheel --output-dir dist
      - name: Upload Build Result
        uses: actions/upload-artifact@v3
        with:
          name: AutoBuild-Windows-${{ github.event.release.tag_name }}
          path: ${{ github.workspace }}/dist/*.*
